# This workflow will install Python and run tox. tox handles all the testing like run locally.

name: test tox CI

on:
  push:
    branches: ["feature/unit_tests"]
  pull_request:
    branches: ["feature/unit_tests"]

# see https://github.com/actions/setup-python?tab=readme-ov-file#recommended-permissions
permissions:
  contents: read # access to check out code and install dependencies

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python: ["3.12", "3.13"]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run tox for pytest
        run: |
          tox -e pytest

  lint_with_ruff:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run tox for lint
        run: |
          tox -e lint

  typecheck_with_mypy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run tox for type
        run: |
          tox -e type